env:
  global:
    - secure: TeFqb814EQDoPAE7ZSb6pzjx+TdC5cCxTn2reN+DO30eTGG04Rs92bOfoj2QhZPIL8eVlNvq5GjXXF53xFGS4gnzZPTaylBNcIJiM54BAXjgQAv2FXUKEs/vvc6T4lKY0fzzc151e5UhmkmYgCbKAqm5HSfi9WlPqLti8k9YbDw=
language: rust
script:
  - chmod +x mktestconfig.sh
  - ./mktestconfig.sh
  - cargo build --verbose
  - cargo build --verbose --features "encode ssl"
  - cargo test --verbose
  - cargo test --verbose --features "encode ssl"
  - cargo doc --verbose
  - cargo doc --verbose --features "encode ssl"
notifications:
  irc:
    channels:
      - "irc.fyrechat.net#vana-commits"
    template:
      - "%{repository_slug}/%{branch} (%{commit} - %{author}): %{message}"
    skip_join: true
after_script:
  - cp -r target/doc doc
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
