env:
  global:
    - secure: aGzqk53//ZQmZ/7Eb8XtlUG3bmwmR5p+RCSqUEz0xUazsYAO0/NRYgEkebXpggvjQCaJFsWWNxfSq5+3bVa43boIChKzshkrqIvF6sO5RxMslNQbb4rabo4GadJYMMFmoG/3h1EwFk3pEsAorNC/M6VVuH9XLKD5dWgvefMqclc=
language: rust
script:
  - chmod +x mktestconfig.sh
  - ./mktestconfig.sh
  - cargo build --verbose --no-default-features
  - cargo build --verbose
  - cargo test --verbose --no-default-features
  - cargo test --verbose
  # - cargo doc --verbose --no-default-features
  # - cargo doc --verbose
notifications:
  irc:
    channels:
      - "irc.fyrechat.net#vana-commits"
    template:
      - "%{repository_slug}/%{branch} (%{commit} - %{author}): %{message}"
    skip_join: true
after_script:
  - cp -r target/doc doc
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
