env:
  global:
    - secure: OB4CMylHbfEPn4znd2xx+99UxGw6M5caM8uNmdU28JwmOydYoZYDniIt5VBR6QrYhNKhbjvEIUZSJkevry3ElL4F18z6/K3WM7J2I/xqbNywRRZ8TJHy+sjk8SXlgivJEkyocrC1KkDF2Jh9SCT3eP0OnTIHSJJd2V0bRxcuvq8= 
language: rust
script:
  - chmod +x mktestconfig.sh
  - ./mktestconfig.sh
  - cargo build --verbose
  - cargo build --verbose --features "encode ssl"
  - cargo test --verbose
  - cargo test --verbose --features "encode ssl"
  - cargo doc --verbose
  - cargo doc --verbose --features "encode ssl"
notifications:
  irc:
    channels:
      - "irc.fyrechat.net#vana-commits"
    template:
      - "%{repository_slug}/%{branch} (%{commit} - %{author}): %{message}"
    skip_join: true
after_script:
  - cp -r target/doc doc
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
