language: rust
rust: stable
sudo: false
script:
  - chmod +x mktestconfig.sh
  - ./mktestconfig.sh
  - cargo build --verbose
  - rustdoc --test README.md -L target/debug/deps
  - cargo test --verbose --features "toml yaml"
  - cargo test --doc
  - cargo test --verbose --no-default-features
notifications:
  email: false
  irc:
    channels:
      - "irc.fyrechat.net#vana-commits"
    template:
      - "%{repository_slug}/%{branch} (%{commit} - %{author}): %{message}"
    skip_join: true
