env:
  global:
    - secure: DHeG/N4iFz1HPU9Pk/lLYD3Rz0WlCtwVi2vEm10Kl8dVbyYrHBmP+q/m21CA2i+PkShJ6RTbj6zMxnBDN9mJ7RGxzqiHhLGawNEQ3fODx7phqZ+Ak9fsHHTXFGy1dtCZfdNGDMDdB8idnK2aKZRj9LWAA10dXu8qlMUjSWxWuzc=
language: rust
script:
  - chmod +x mktestconfig.sh
  - ./mktestconfig.sh
  - cargo build --verbose
  - cargo build --verbose --features "encode ssl"
  - cargo test --verbose
  - cargo test --verbose --features "encode ssl" 
  - cargo doc --verbose
  - cargo doc --verbose --features "encode ssl"
notifications:
  irc:
    channels:
      - "irc.fyrechat.net#vana-commits"
    template:
      - "%{repository_slug}/%{branch} (%{commit} - %{author}): %{message}"
    skip_join: true
after_script:
  - cp -r target/doc doc
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
