env:
  global:
    - secure: Ykd7JchE6cvSNb5Ej6p5BfytzvWfW942PgCPyUwxDhfKnQoq8Ws4TISPu7RRbqL1Bje4vF3JTis/N9phJgcFhECizfLO4PvMoGcN8a7S+kLnJ/IXDaDwAQDrR3gl0Ean6Ly4prVFfw0nrzPRUacqtbJbVvSGvm1myrcATljvgFg=
language: rust
script:
  - chmod +x mktestconfig.sh
  - ./mktestconfig.sh
  - cargo build --verbose
  - cargo build --verbose --features "encode ssl"
  - cargo test --verbose
  - cargo test --verbose --features "encode ssl" 
  - cargo doc --verbose
  - cargo doc --verbose --features "encode ssl"
notifications:
  irc:
    channels:
      - "irc.fyrechat.net#vana-commits"
    template:
      - "%{repository_slug}/%{branch} (%{commit} - %{author}): %{message}"
    skip_join: true
after_script:
  - cp -r target/doc doc
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
