[package]

name = "irc"
version = "0.11.6"
description = "A simple, thread-safe IRC client library."
authors = ["Aaron Weiss <aaronweiss74@gmail.com>"]
license = "CC0-1.0"
keywords = ["irc", "client", "thread-safe"]
documentation = "http://aatxe.github.io/irc/irc/"
repository = "https://github.com/aatxe/irc"
readme = "README.md"

[features]

default = ["ctcp"]
ctcp = []
nochanlists = []

[dependencies]
rustc-serialize = "0.3"
time = "0.1"
encoding = "0.2"
native-tls = "0.1"
tokio-core = "0.1"
tokio-service = "0.1"
tokio-tls = "0.1"
