[package]

name = "irc"
version = "0.3.0"
description = "A simple, thread-safe IRC client library."
authors = ["Aaron Weiss <aaronweiss74@gmail.com>"]
license = "Unlicense"
keywords = ["irc", "client", "thread-safe"]
documentation = "http://www.rust-ci.org/aaronweiss74/irc/doc/irc/"
repository = "https://github.com/aaronweiss74/irc"
readme = "README.md"

[features]

ssl = ["openssl"]

[dependencies.encoding]

encoding = "~0.2.4"

[dependencies.openssl]

openssl = "~0.2.0"
optional = true
