[package]

name = "irc"
version = "0.11.8"
description = "A simple, thread-safe IRC client library."
authors = ["Aaron Weiss <aaronweiss74@gmail.com>"]
license = "CC0-1.0"
keywords = ["irc", "client", "thread-safe"]
documentation = "http://aatxe.github.io/irc/irc/"
repository = "https://github.com/aatxe/irc"
readme = "README.md"

[features]

default = ["ctcp"]
ctcp = []
nochanlists = []

[dependencies]
bufstream = "0.1"
bytes = "0.4"
error-chain = "0.10"
encoding = "0.2"
futures = "0.1"
native-tls = "0.1"
time = "0.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tokio-core = "0.1"
tokio-io = "0.1"
tokio-service = "0.1"
tokio-tls = "0.1"
