[package]

name = "irc"
version = "0.7.5"
description = "A simple, thread-safe IRC client library."
authors = ["Aaron Weiss <aaronweiss74@gmail.com>"]
license = "Unlicense"
keywords = ["irc", "client", "thread-safe"]
documentation = "http://www.rust-ci.org/aatxe/irc/doc/irc/"
repository = "https://github.com/aatxe/irc"
readme = "README.md"

[features]

default = ["ctcp", "encode", "ssl"]
ctcp = ["time"]
encode = ["encoding"]
ssl = ["openssl"]

[dependencies.rustc-serialize]
rustc-serialize = "~0.2.3"

[dependencies.time]

time = "~0.1.9"
optional = true

[dependencies.encoding]

encoding = "~0.2.14"
optional = true

[dependencies.openssl]

openssl = "~0.2.12"
optional = true
