[package]

name = "irc"
version = "0.9.0"
description = "A simple, thread-safe IRC client library."
authors = ["Aaron Weiss <aaronweiss74@gmail.com>"]
license = "CC0-1.0"
keywords = ["irc", "client", "thread-safe"]
documentation = "http://aatxe.github.io/irc/irc/"
repository = "https://github.com/aatxe/irc"
readme = "README.md"

[features]

default = ["ctcp", "encode", "ssl"]
ctcp = ["time"]
encode = ["encoding"]
ssl = ["openssl"]
nochanlists = []

[dependencies.rustc-serialize]
rustc-serialize = "~0.3.15"

[dependencies.time]

time = "~0.1.31"
optional = true

[dependencies.encoding]

encoding = "~0.2.32"
optional = true

[dependencies.openssl]

openssl = "~0.6.4"
optional = true
