[package]

name = "irc"
version = "0.5.6"
description = "A simple, thread-safe IRC client library."
authors = ["Aaron Weiss <aaronweiss74@gmail.com>"]
license = "Unlicense"
keywords = ["irc", "client", "thread-safe"]
documentation = "http://aaronweiss74.github.io/irc/irc/"
repository = "https://github.com/aaronweiss74/irc"
readme = "README.md"

[features]

encode = ["encoding"]
ssl = ["openssl"]

[dependencies.encoding]

encoding = "~0.2.6"
optional = true

[dependencies.openssl]

openssl = "~0.2.4"
optional = true
