[package]

name = "irc"
version = "0.6.0"
description = "A simple, thread-safe IRC client library."
authors = ["Aaron Weiss <aaronweiss74@gmail.com>"]
license = "Unlicense"
keywords = ["irc", "client", "thread-safe"]
documentation = "http://www.rust-ci.org/aatxe/irc/doc/irc/"
repository = "https://github.com/aatxe/irc"
readme = "README.md"

[features]

ctcp = ["time"]
encode = ["encoding"]
ssl = ["openssl"]

[dependencies.time]

time = "~0.1.3"
optional = true

[dependencies.encoding]

encoding = "~0.2.8"
optional = true

[dependencies.openssl]

openssl = "~0.2.6"
optional = true
